# Generated by Django 4.2.4 on 2024-05-02 14:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cage',
            fields=[
                ('cage_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('cage_name', models.CharField(max_length=20)),
                ('number_of_duts', models.SmallIntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=20, null=True)),
                ('product', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chamber',
            fields=[
                ('chamber_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('chamber_name', models.CharField(max_length=20, unique=True)),
                ('cooling_type', models.CharField(blank=True, max_length=20, null=True)),
                ('power', models.CharField(blank=True, max_length=20, null=True)),
                ('humidity', models.CharField(blank=True, max_length=3, null=True, verbose_name='Humidity')),
                ('operation_team', models.CharField(blank=True, max_length=20, null=True)),
                ('working_condition', models.CharField(blank=True, max_length=50, null=True, verbose_name='Working Condition')),
                ('rate', models.FloatField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=20, null=True)),
                ('heating_power', models.SmallIntegerField(blank=True, null=True)),
                ('cooling_power', models.SmallIntegerField(blank=True, null=True)),
                ('heating_gradient', models.FloatField(blank=True, null=True)),
                ('max_daily_hours', models.SmallIntegerField(blank=True, null=True)),
                ('billing_category', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DAR',
            fields=[
                ('dar_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('dar_name', models.CharField(max_length=40, unique=True)),
                ('ac_input_voltage', models.CharField(blank=True, max_length=20, null=True)),
                ('ac_input_phase', models.CharField(blank=True, max_length=30, null=True)),
                ('operation_team', models.CharField(blank=True, max_length=20, null=True)),
                ('working_condition', models.CharField(blank=True, max_length=50, null=True, verbose_name='Working Condition')),
            ],
        ),
        migrations.CreateModel(
            name='DUT',
            fields=[
                ('dut_name', models.CharField(max_length=12, unique=True, verbose_name='DUT name')),
                ('received_date', models.DateField(blank=True, null=True)),
                ('storage_date', models.DateField(blank=True, null=True)),
                ('storage_bin', models.CharField(blank=True, max_length=20, null=True)),
                ('dut_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='DUT name')),
            ],
        ),
        migrations.CreateModel(
            name='Fluid',
            fields=[
                ('fluid_name', models.CharField(max_length=30)),
                ('manufacturer', models.CharField(blank=True, max_length=20, null=True)),
                ('storage_location', models.CharField(blank=True, max_length=20, null=True)),
                ('fluid_id', models.SmallAutoField(primary_key=True, serialize=False, verbose_name='Fluid name')),
            ],
        ),
        migrations.CreateModel(
            name='Harness',
            fields=[
                ('harness_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('harness_name', models.CharField(max_length=50, unique=True)),
                ('storage_location', models.CharField(blank=True, max_length=20, null=True)),
                ('test_screening_result', models.CharField(blank=True, max_length=10, null=True, verbose_name='Test Screening Result')),
                ('harness_connector_condition', models.CharField(blank=True, max_length=10, null=True, verbose_name='Harness Connector Condition')),
                ('insulation_condition', models.CharField(blank=True, max_length=10, null=True, verbose_name='Insulation Condition')),
                ('rtv_condition', models.CharField(blank=True, max_length=10, null=True, verbose_name='RTV Condition')),
                ('dunk_testing', models.CharField(blank=True, max_length=10, null=True, verbose_name='Dunk Testing')),
                ('average_resistance', models.FloatField(blank=True, null=True)),
                ('comments', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('lab_name', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=15, null=True)),
                ('supervisor', models.CharField(blank=True, max_length=25, null=True)),
                ('lab_id', models.SmallAutoField(primary_key=True, serialize=False, verbose_name='Lab')),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('laptop_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('laptop_name', models.CharField(max_length=20, unique=True)),
                ('brand', models.CharField(blank=True, max_length=20, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=30, null=True)),
                ('system_type', models.CharField(blank=True, max_length=20, null=True)),
                ('ram_slot1', models.SmallIntegerField(blank=True, null=True)),
                ('ram_slot2', models.SmallIntegerField(blank=True, null=True)),
                ('total_ram', models.SmallIntegerField(blank=True, null=True)),
                ('ram_limit', models.SmallIntegerField(blank=True, null=True)),
                ('ram_type', models.CharField(blank=True, max_length=20, null=True)),
                ('ram_upgrade_date', models.DateField(blank=True, null=True)),
                ('mfg_year', models.SmallIntegerField(blank=True, null=True)),
                ('model', models.CharField(blank=True, max_length=30, null=True)),
                ('model_number', models.CharField(blank=True, max_length=30, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=30, null=True)),
                ('operating_system', models.CharField(blank=True, max_length=20, null=True)),
                ('keyboard_cover', models.CharField(blank=True, max_length=10, null=True, verbose_name='Keyboard Cover')),
                ('comments', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('product_family', models.CharField(blank=True, max_length=10, null=True)),
                ('platform', models.CharField(blank=True, max_length=15, null=True)),
                ('communication_protocol', models.CharField(blank=True, max_length=15, null=True)),
                ('voltage', models.CharField(blank=True, max_length=3, null=True)),
                ('variant', models.CharField(blank=True, max_length=30, null=True)),
                ('product_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Product')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('program_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Program')),
                ('status', models.CharField(blank=True, max_length=20, null=True, verbose_name='Status')),
                ('phase', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phase')),
                ('enterproj_id', models.IntegerField(blank=True, null=True)),
                ('wbs_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='WBS')),
                ('oem', models.CharField(blank=True, max_length=20, null=True, verbose_name='OEM')),
                ('program_id', models.SmallAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('skill', models.CharField(max_length=25, unique=True)),
                ('skill_id', models.SmallAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('technician_name', models.CharField(max_length=30)),
                ('technician_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('lab_id', models.ForeignKey(blank=True, db_column='lab_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.lab', verbose_name='Lab')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('priority', models.SmallIntegerField(blank=True, null=True)),
                ('scheduling', models.CharField(blank=True, max_length=15, null=True)),
                ('status', models.CharField(blank=True, max_length=15, null=True)),
                ('test_description', models.CharField(blank=True, max_length=100, null=True)),
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('targeted_start', models.DateField(blank=True, null=True)),
                ('targeted_end', models.DateField(blank=True, null=True)),
                ('supervisor_comments', models.CharField(blank=True, max_length=4000, null=True)),
                ('hours_planned', models.SmallIntegerField(blank=True, null=True)),
                ('total_hours', models.SmallIntegerField(blank=True, null=True)),
                ('cage_id', models.ForeignKey(db_column='cage_id', on_delete=django.db.models.deletion.CASCADE, to='database.cage', verbose_name='Cage')),
                ('chamber_id', models.ForeignKey(db_column='chamber_id', on_delete=django.db.models.deletion.CASCADE, to='database.chamber', verbose_name='Chamber')),
                ('dar_id', models.ForeignKey(db_column='dar_id', on_delete=django.db.models.deletion.CASCADE, to='database.dar', verbose_name='DAR')),
                ('lab_id', models.ForeignKey(db_column='lab_id', on_delete=django.db.models.deletion.CASCADE, to='database.lab', verbose_name='Lab')),
                ('product_id', models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.product', verbose_name='Product')),
                ('program_id', models.ForeignKey(blank=True, db_column='program_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='database.program', verbose_name='Program')),
                ('technician_id', models.ForeignKey(db_column='technician_id', on_delete=django.db.models.deletion.CASCADE, to='database.technician', verbose_name='Technician')),
            ],
        ),
        migrations.CreateModel(
            name='TestType',
            fields=[
                ('test_type_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('test_name', models.CharField(db_column='test_type', max_length=50, verbose_name='test_type')),
            ],
        ),
        migrations.CreateModel(
            name='TestMap',
            fields=[
                ('test_map_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Test Map name')),
                ('tr', models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='TR')),
                ('test_map_id', models.AutoField(primary_key=True, serialize=False)),
                ('program_id', models.ForeignKey(blank=True, db_column='program_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='database.program', verbose_name='Program')),
            ],
        ),
        migrations.CreateModel(
            name='Test_Harness',
            fields=[
                ('circuit_number', models.SmallIntegerField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_inserted', models.DateTimeField()),
                ('date_removed', models.DateTimeField(blank=True, null=True)),
                ('harness_id', models.ForeignKey(db_column='harness_id', on_delete=django.db.models.deletion.CASCADE, to='database.harness', verbose_name='Harness name')),
                ('test_id', models.ForeignKey(db_column='test_id', on_delete=django.db.models.deletion.CASCADE, to='database.test', verbose_name='Test')),
            ],
        ),
        migrations.CreateModel(
            name='Test_DUT',
            fields=[
                ('circuit_number', models.SmallIntegerField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_inserted', models.DateTimeField()),
                ('date_removed', models.DateTimeField(blank=True, null=True)),
                ('dut_id', models.ForeignKey(db_column='dut_id', on_delete=django.db.models.deletion.CASCADE, to='database.dut', verbose_name='DUT name')),
                ('test_id', models.ForeignKey(db_column='test_id', on_delete=django.db.models.deletion.CASCADE, to='database.test', verbose_name='Test')),
            ],
        ),
        migrations.CreateModel(
            name='Test_Chamber',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('chamber_id', models.ForeignKey(blank=True, db_column='chamber_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='database.chamber', verbose_name='Chamber')),
                ('test_type_id', models.ForeignKey(blank=True, db_column='test_type_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='database.testtype', verbose_name='Test')),
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='test_map_id',
            field=models.ForeignKey(db_column='test_map_id', on_delete=django.db.models.deletion.CASCADE, to='database.testmap', verbose_name='Leg'),
        ),
        migrations.AddField(
            model_name='test',
            name='test_type_id',
            field=models.ForeignKey(db_column='test_type_id', on_delete=django.db.models.deletion.CASCADE, to='database.testtype', verbose_name='Test Type'),
        ),
        migrations.CreateModel(
            name='Technician_Skill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('skill_id', models.ForeignKey(db_column='skill_id', on_delete=django.db.models.deletion.CASCADE, to='database.skill', verbose_name='Skill')),
                ('technician_id', models.ForeignKey(db_column='technician_id', on_delete=django.db.models.deletion.CASCADE, to='database.technician', verbose_name='Technician name')),
            ],
        ),
        migrations.CreateModel(
            name='Subcomponent',
            fields=[
                ('component_name', models.CharField(max_length=100)),
                ('component_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Subcomponent')),
                ('dut_id', models.ForeignKey(blank=True, db_column='dut_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='database.dut', verbose_name='DUT name')),
            ],
        ),
        migrations.CreateModel(
            name='Program_Fluid',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fluid_id', models.ForeignKey(blank=True, db_column='fluid_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='database.fluid', verbose_name='Fluid')),
                ('program_id', models.ForeignKey(blank=True, db_column='program_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='database.program', verbose_name='Program')),
            ],
        ),
        migrations.CreateModel(
            name='Program_DAR',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dar_id', models.ForeignKey(blank=True, db_column='dar_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='database.dar', verbose_name='DAR')),
                ('program_id', models.ForeignKey(blank=True, db_column='program_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='database.program', verbose_name='Program')),
            ],
        ),
        migrations.CreateModel(
            name='Program_Cage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cage_id', models.ForeignKey(blank=True, db_column='cage_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='database.cage', verbose_name='Cage')),
                ('program_id', models.ForeignKey(blank=True, db_column='program_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='database.program', verbose_name='Program')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='program_id',
            field=models.ForeignKey(blank=True, db_column='program_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='database.program', verbose_name='Program'),
        ),
        migrations.AddField(
            model_name='dut',
            name='product_id',
            field=models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.product', verbose_name='Product name'),
        ),
        migrations.CreateModel(
            name='DARChannel',
            fields=[
                ('channel_id', models.AutoField(primary_key=True, serialize=False)),
                ('channel_number', models.SmallIntegerField(blank=True, null=True)),
                ('number_of_duts', models.SmallIntegerField(blank=True, null=True)),
                ('power_supply_type', models.CharField(blank=True, max_length=20, null=True)),
                ('power_supply_48V', models.SmallIntegerField(blank=True, null=True)),
                ('power_supply_12V', models.SmallIntegerField(blank=True, null=True)),
                ('max_current_48V', models.CharField(blank=True, max_length=10, null=True)),
                ('max_current_12V', models.CharField(blank=True, max_length=10, null=True)),
                ('power_supply_model', models.CharField(blank=True, max_length=50, null=True)),
                ('N_eWP_Primary', models.SmallIntegerField(blank=True, null=True)),
                ('N_eWP_Med_Aux', models.SmallIntegerField(blank=True, null=True)),
                ('N_eTMOP', models.SmallIntegerField(blank=True, null=True)),
                ('N_eCF', models.SmallIntegerField(blank=True, null=True)),
                ('lin', models.CharField(blank=True, max_length=50, null=True, verbose_name='LIN')),
                ('pwn', models.CharField(blank=True, max_length=50, null=True, verbose_name='PWN')),
                ('can', models.CharField(blank=True, max_length=50, null=True, verbose_name='CAN')),
                ('pressure_transducer_inlet', models.CharField(blank=True, max_length=50, null=True)),
                ('pressure_transducer_outlet', models.CharField(blank=True, max_length=50, null=True)),
                ('dar_id', models.ForeignKey(blank=True, db_column='dar_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='database.dar', verbose_name='DAR')),
            ],
        ),
        migrations.CreateModel(
            name='DAR_Laptop',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('dar_id', models.ForeignKey(blank=True, db_column='dar_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='database.dar', verbose_name='DAR')),
                ('laptop_id', models.ForeignKey(blank=True, db_column='laptop_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='database.laptop', verbose_name='Laptop')),
            ],
        ),
        migrations.AddField(
            model_name='dar',
            name='lab_id',
            field=models.ForeignKey(blank=True, db_column='lab_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.lab', verbose_name='Lab'),
        ),
        migrations.CreateModel(
            name='ChamberLogInfo',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pretest_inspection_and_photo', models.CharField(blank=True, max_length=10, null=True, verbose_name='Pretest Inspection and Photo')),
                ('setup_photo', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('system_pressure', models.FloatField(blank=True, null=True)),
                ('voltage', models.FloatField(blank=True, null=True)),
                ('system_restriction_target', models.CharField(blank=True, max_length=50, null=True)),
                ('system_restriction_record', models.CharField(blank=True, max_length=10, null=True, verbose_name='System Restriction Record')),
                ('trial_run_record_and_process', models.CharField(blank=True, max_length=10, null=True, verbose_name='Trial Run Record And Process')),
                ('special_requirements', models.CharField(blank=True, max_length=300, null=True)),
                ('coolant', models.CharField(blank=True, max_length=100, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('test_profile', models.CharField(blank=True, max_length=300, null=True)),
                ('shaker_profile', models.CharField(blank=True, max_length=300, null=True)),
                ('chamber_profile', models.CharField(blank=True, max_length=300, null=True)),
                ('pump_profile', models.CharField(blank=True, max_length=300, null=True)),
                ('comments', models.CharField(blank=True, max_length=4000, null=True)),
                ('chamber_id', models.ForeignKey(blank=True, db_column='chamber_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.chamber', verbose_name='Chamber')),
                ('program_id', models.ForeignKey(blank=True, db_column='program_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.program', verbose_name='Program')),
                ('technician_id', models.ForeignKey(blank=True, db_column='technician_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.technician', verbose_name='Technician')),
                ('test_id', models.ForeignKey(db_column='test_id', on_delete=django.db.models.deletion.CASCADE, to='database.test', verbose_name='Test')),
            ],
        ),
        migrations.CreateModel(
            name='ChamberLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('circuit_number', models.SmallIntegerField()),
                ('total_hours', models.SmallIntegerField()),
                ('status', models.CharField(blank=True, max_length=20, null=True, verbose_name='Status')),
                ('comments', models.CharField(blank=True, max_length=300, null=True)),
                ('technician', models.CharField(blank=True, max_length=100, null=True)),
                ('shaker_direction', models.CharField(blank=True, max_length=100, null=True)),
                ('cage_id', models.ForeignKey(blank=True, db_column='cage_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='database.cage', verbose_name='Cage')),
                ('chamber_id', models.ForeignKey(db_column='chamber_id', on_delete=django.db.models.deletion.CASCADE, to='database.chamber', verbose_name='Chamber')),
                ('dar_id', models.ForeignKey(blank=True, db_column='dar_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='database.dar', verbose_name='DAR')),
                ('log_id', models.ForeignKey(db_column='log_id', on_delete=django.db.models.deletion.CASCADE, to='database.chamberloginfo', verbose_name='Log')),
            ],
        ),
        migrations.AddField(
            model_name='chamber',
            name='lab_id',
            field=models.ForeignKey(blank=True, db_column='lab_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.lab'),
        ),
    ]
