# Generated by Django 4.2.4 on 2024-05-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='darchannel',
            name='N_eCF',
        ),
        migrations.RemoveField(
            model_name='darchannel',
            name='N_eTMOP',
        ),
        migrations.RemoveField(
            model_name='darchannel',
            name='N_eWP_Med_Aux',
        ),
        migrations.RemoveField(
            model_name='darchannel',
            name='N_eWP_Primary',
        ),
        migrations.AddField(
            model_name='darchannel',
            name='eCF',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='darchannel',
            name='eTMOP',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='darchannel',
            name='eWP_Med_Aux',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='darchannel',
            name='eWP_Primary',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
