# Generated by Django 4.2.4 on 2024-04-18 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_rename_test_screening_resutl_harness_test_screening_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamberloginfo',
            name='comments',
            field=models.CharField(max_length=4000, null=True),
        ),
    ]
