# Generated by Django 4.2.4 on 2024-05-03 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_remove_darchannel_n_ecf_remove_darchannel_n_etmop_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptop',
            name='ram_limit',
        ),
        migrations.AddField(
            model_name='laptop',
            name='dar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.dar', verbose_name='DAR'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='processor_type',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Processor Type (32 or 64)'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='status',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='teamviewer_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='keyboard_cover',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Keyboard Cover'),
        ),
        migrations.DeleteModel(
            name='DAR_Laptop',
        ),
    ]
