# Generated by Django 4.2.4 on 2024-04-18 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_chamberloginfo_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='product_id',
            field=models.ForeignKey(db_column='product', null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.product'),
        ),
    ]
