# Generated by Django 4.2.4 on 2024-04-18 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_alter_test_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='cage_id',
            field=models.ForeignKey(db_column='cage_id', on_delete=django.db.models.deletion.CASCADE, to='database.cage', verbose_name='Cage'),
        ),
        migrations.AlterField(
            model_name='test',
            name='chamber_id',
            field=models.ForeignKey(db_column='chamber_id', on_delete=django.db.models.deletion.CASCADE, to='database.chamber', verbose_name='Chamber'),
        ),
        migrations.AlterField(
            model_name='test',
            name='product_id',
            field=models.ForeignKey(db_column='product_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='test',
            name='program_id',
            field=models.ForeignKey(db_column='program_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='database.program', verbose_name='Program'),
        ),
        migrations.AlterField(
            model_name='test',
            name='technician_id',
            field=models.ForeignKey(db_column='technician_id', on_delete=django.db.models.deletion.CASCADE, to='database.technician', verbose_name='Technician'),
        ),
    ]
