# Generated by Django 4.2.4 on 2024-04-18 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_alter_test_cage_id_alter_test_chamber_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamberlog',
            name='cage_id',
            field=models.ForeignKey(db_column='cage_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='database.cage', verbose_name='Cage'),
        ),
        migrations.AlterField(
            model_name='chamberlog',
            name='chamber_id',
            field=models.ForeignKey(db_column='chamber_id', on_delete=django.db.models.deletion.CASCADE, to='database.chamber', verbose_name='Chamber'),
        ),
        migrations.AlterField(
            model_name='chamberlog',
            name='dar_id',
            field=models.ForeignKey(db_column='dar_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='database.dar', verbose_name='DAR'),
        ),
        migrations.AlterField(
            model_name='chamberlog',
            name='log_id',
            field=models.ForeignKey(db_column='log_id', on_delete=django.db.models.deletion.CASCADE, to='database.chamberloginfo', verbose_name='Log'),
        ),
        migrations.AlterField(
            model_name='chamberloginfo',
            name='chamber_id',
            field=models.ForeignKey(db_column='chamber_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.chamber', verbose_name='Chamber'),
        ),
        migrations.AlterField(
            model_name='chamberloginfo',
            name='program_id',
            field=models.ForeignKey(db_column='program_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.program', verbose_name='Program'),
        ),
        migrations.AlterField(
            model_name='chamberloginfo',
            name='technician_id',
            field=models.ForeignKey(db_column='technician_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.technician', verbose_name='Technician'),
        ),
        migrations.AlterField(
            model_name='chamberloginfo',
            name='test_id',
            field=models.ForeignKey(db_column='test_id', on_delete=django.db.models.deletion.CASCADE, to='database.test', verbose_name='Test'),
        ),
        migrations.AlterField(
            model_name='dar',
            name='lab_id',
            field=models.ForeignKey(db_column='lab_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.lab', verbose_name='Lab'),
        ),
        migrations.AlterField(
            model_name='dar_laptop',
            name='dar_id',
            field=models.ForeignKey(db_column='dar_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='database.dar', verbose_name='DAR'),
        ),
        migrations.AlterField(
            model_name='dar_laptop',
            name='laptop_id',
            field=models.ForeignKey(db_column='laptop_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='database.laptop', verbose_name='Laptop'),
        ),
        migrations.AlterField(
            model_name='dut',
            name='dut_id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='DUT name'),
        ),
        migrations.AlterField(
            model_name='dut',
            name='dut_name',
            field=models.CharField(max_length=12, unique=True, verbose_name='DUT name'),
        ),
        migrations.AlterField(
            model_name='dut',
            name='product_id',
            field=models.ForeignKey(db_column='product_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.product', verbose_name='Product name'),
        ),
        migrations.AlterField(
            model_name='fluid',
            name='fluid_id',
            field=models.SmallAutoField(primary_key=True, serialize=False, verbose_name='Fluid name'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='lab_id',
            field=models.SmallAutoField(primary_key=True, serialize=False, verbose_name='Lab'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='program_id',
            field=models.ForeignKey(db_column='program_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='database.program', verbose_name='Program'),
        ),
        migrations.AlterField(
            model_name='program',
            name='oem',
            field=models.CharField(max_length=20, null=True, verbose_name='OEM'),
        ),
        migrations.AlterField(
            model_name='program',
            name='wbs_number',
            field=models.CharField(max_length=30, null=True, verbose_name='WBS'),
        ),
        migrations.AlterField(
            model_name='program_cage',
            name='cage_id',
            field=models.ForeignKey(db_column='cage_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='database.cage', verbose_name='Cage'),
        ),
        migrations.AlterField(
            model_name='program_cage',
            name='program_id',
            field=models.ForeignKey(db_column='program_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='database.program', verbose_name='Program'),
        ),
        migrations.AlterField(
            model_name='program_dar',
            name='dar_id',
            field=models.ForeignKey(db_column='dar_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='database.dar', verbose_name='DAR'),
        ),
        migrations.AlterField(
            model_name='program_dar',
            name='program_id',
            field=models.ForeignKey(db_column='program_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='database.program', verbose_name='Program'),
        ),
        migrations.AlterField(
            model_name='program_fluid',
            name='fluid_id',
            field=models.ForeignKey(db_column='fluid_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='database.fluid', verbose_name='Fluid'),
        ),
        migrations.AlterField(
            model_name='program_fluid',
            name='program_id',
            field=models.ForeignKey(db_column='program_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='database.program', verbose_name='Program'),
        ),
        migrations.AlterField(
            model_name='subcomponent',
            name='component_id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='Subcomponent'),
        ),
        migrations.AlterField(
            model_name='subcomponent',
            name='dut_id',
            field=models.ForeignKey(db_column='dut_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='database.dut', verbose_name='DUT name'),
        ),
        migrations.AlterField(
            model_name='technician',
            name='lab_id',
            field=models.ForeignKey(db_column='lab_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.lab', verbose_name='Lab'),
        ),
        migrations.AlterField(
            model_name='technician_skill',
            name='skill_id',
            field=models.ForeignKey(db_column='skill_id', on_delete=django.db.models.deletion.CASCADE, to='database.skill', verbose_name='Skill'),
        ),
        migrations.AlterField(
            model_name='technician_skill',
            name='technician_id',
            field=models.ForeignKey(db_column='technician_id', on_delete=django.db.models.deletion.CASCADE, to='database.technician', verbose_name='Technician name'),
        ),
        migrations.AlterField(
            model_name='test_chamber',
            name='chamber_id',
            field=models.ForeignKey(db_column='chamber_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='database.chamber', verbose_name='Chamber'),
        ),
        migrations.AlterField(
            model_name='test_chamber',
            name='test_type_id',
            field=models.ForeignKey(db_column='test_type_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='database.testtype', verbose_name='Test'),
        ),
        migrations.AlterField(
            model_name='test_dut',
            name='dut_id',
            field=models.ForeignKey(db_column='dut_id', on_delete=django.db.models.deletion.CASCADE, to='database.dut', verbose_name='DUT name'),
        ),
        migrations.AlterField(
            model_name='test_dut',
            name='test_id',
            field=models.ForeignKey(db_column='test_id', on_delete=django.db.models.deletion.CASCADE, to='database.test', verbose_name='Test'),
        ),
        migrations.AlterField(
            model_name='test_harness',
            name='harness_id',
            field=models.ForeignKey(db_column='harness_id', on_delete=django.db.models.deletion.CASCADE, to='database.harness', verbose_name='Harness name'),
        ),
        migrations.AlterField(
            model_name='test_harness',
            name='test_id',
            field=models.ForeignKey(db_column='test_id', on_delete=django.db.models.deletion.CASCADE, to='database.test', verbose_name='Test'),
        ),
        migrations.AlterField(
            model_name='testmap',
            name='program_id',
            field=models.ForeignKey(db_column='program_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='database.program', verbose_name='Program'),
        ),
        migrations.AlterField(
            model_name='testmap',
            name='test_map_name',
            field=models.CharField(max_length=30, null=True, verbose_name='Test Map name'),
        ),
        migrations.AlterField(
            model_name='testmap',
            name='tr',
            field=models.CharField(max_length=14, null=True, unique=True, verbose_name='TR'),
        ),
    ]
