# Generated by Django 4.2.4 on 2024-04-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_alter_cage_number_of_duts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamber',
            name='humidity',
            field=models.BooleanField(blank=True, max_length=10, null=True, verbose_name='Humidity'),
        ),
        migrations.AlterField(
            model_name='chamber',
            name='power',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
