# Generated by Django 4.2.4 on 2024-05-01 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_alter_chamber_humidity_alter_chamber_power'),
    ]

    operations = [
        migrations.AlterField(
            model_name='darchannel',
            name='dar_id',
            field=models.ForeignKey(blank=True, db_column='dar_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='database.dar', verbose_name='DAR'),
        ),
        migrations.AlterField(
            model_name='testtype',
            name='test_name',
            field=models.CharField(db_column='test_type', max_length=20, unique=True, verbose_name='test_type'),
        ),
    ]
