# Generated by Django 4.2.4 on 2024-05-01 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_alter_darchannel_dar_id_alter_testtype_test_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cage',
            name='category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cage',
            name='product',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='darchannel',
            name='N_eCF',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='darchannel',
            name='N_eTMOP',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='darchannel',
            name='N_eWP_Med_Aux',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='darchannel',
            name='N_eWP_Primary',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='darchannel',
            name='number_of_duts',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='darchannel',
            name='power_supply_model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='darchannel',
            name='pressure_transducer_inlet',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='darchannel',
            name='pressure_transducer_outlet',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='test_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_type_id',
            field=models.ForeignKey(db_column='test_type_id', on_delete=django.db.models.deletion.CASCADE, to='database.testtype', verbose_name='Test Type'),
        ),
    ]
